import Mathlib.Data.Nat.Prime.Defs
import Canonical

-- This is really hard at the dependent type theory level, so Canonical isn't
-- really the right tool for the job
theorem two_prime : Nat.Prime 2 := by
  canonical +debug

-- This (and other semi-tedious algebraic identities) are likely not a job for
-- Canonical since you can just use ring (the proof terms generated by ring are
-- already large, so it's not so surprising that Canonical would need a long
-- time)
theorem foil_nat (a b : Nat) : (a + b) * (a + b) = a * a + 2 * a * b + b * b := by
  sorry
  -- canonical 5 [Nat.right_distrib, Nat.left_distrib, Nat.mul_comm]

theorem exists_nontrivial_triple : ∃ a b c : Nat, 1 < a ∧ a * a + b * b = c * c := by
  sorry
